#!/bin/sh
# Sync the distributable fhtml skill from its sources.
#
#   llms.md                ──▶ skills/fhtml/references/language.md   (verbatim copy)
#   SKILL.md + llms.md     ──▶ skills/fhtml/AGENTS.md                (single-file form)
#   skills/fhtml/          ──▶ .claude/skills/fhtml/                 (local dogfood mirror)
#
# Generated files are committed so installing the skill is a plain copy —
# this script is the sync mechanism, not a build step consumers run.
# `--check` diffs instead of writing (CI guard against drift).
set -eu

cd "$(dirname "$0")/.."

SKILL=skills/fhtml
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

mkdir -p "$STAGE/references"

cp llms.md "$STAGE/references/language.md"
cp "$SKILL/SKILL.md" "$STAGE/SKILL.md"
cp "$SKILL/references/examples.md" "$STAGE/references/examples.md"

# AGENTS.md = a provenance note + SKILL.md body (YAML frontmatter stripped:
# delete through the second `---` line) + the full language reference.
{
  printf '# fhtml — agent skill (single-file form)\n\n'
  printf 'Generated by skills/build.sh from skills/fhtml/SKILL.md + llms.md — do not edit.\n'
  printf 'Practice files mentioned below (references/language.md) are inlined at the end\n'
  printf 'of this file; references/examples.md ships with the full skill directory.\n'
  awk 'f>=2 {print} /^---$/ {f++}' "$SKILL/SKILL.md"
  printf '\n---\n\n'
  cat llms.md
} > "$STAGE/AGENTS.md"

if [ "${1:-}" = "--check" ]; then
  fail=0
  for f in SKILL.md AGENTS.md references/language.md references/examples.md; do
    for dst in "$SKILL/$f" ".claude/skills/fhtml/$f"; do
      if ! diff -q "$STAGE/$f" "$dst" >/dev/null 2>&1; then
        echo "drift: $dst is out of sync (run skills/build.sh)" >&2
        fail=1
      fi
    done
  done
  exit "$fail"
fi

cp "$STAGE/references/language.md" "$SKILL/references/language.md"
cp "$STAGE/AGENTS.md" "$SKILL/AGENTS.md"

# Local dogfood mirror: a real copy (not a symlink) so archives and
# skill loaders that refuse symlinks both work.
rm -rf .claude/skills/fhtml
mkdir -p .claude/skills/fhtml/references
cp "$SKILL/SKILL.md" "$SKILL/AGENTS.md" .claude/skills/fhtml/
cp "$SKILL/references/language.md" "$SKILL/references/examples.md" .claude/skills/fhtml/references/

echo "synced → $SKILL/{references/language.md,AGENTS.md}, .claude/skills/fhtml/"
